//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povilion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empoloy
    {
        public Empoloy()
        {
            this.Rents = new HashSet<Rent>();
        }
    
        public int Emp_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int post_id { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Poste Poste { get; set; }
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
