//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povilion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poste
    {
        public Poste()
        {
            this.Empoloys = new HashSet<Empoloy>();
        }
    
        public int post_id { get; set; }
        public string desc_postes { get; set; }
    
        public virtual ICollection<Empoloy> Empoloys { get; set; }
    }
}
