//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povilion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Centers
    {
        public Shop_Centers()
        {
            this.pavilions = new HashSet<pavilion>();
        }
    
        public int Shop_Centr_id { get; set; }
        public string Name { get; set; }
        public int Status_id { get; set; }
        public int povil_count { get; set; }
        public string City { get; set; }
        public decimal Cost { get; set; }
        public int num_of_floors { get; set; }
        public Nullable<float> ratio { get; set; }
        public byte[] Icon { get; set; }
    
        public virtual ICollection<pavilion> pavilions { get; set; }
        public virtual status_shop status_shop { get; set; }
    }
}
