//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povilion
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_povil
    {
        public status_povil()
        {
            this.pavilions = new HashSet<pavilion>();
        }
    
        public int status_id { get; set; }
        public string desc_status { get; set; }
    
        public virtual ICollection<pavilion> pavilions { get; set; }
    }
}
