//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povilion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.Rents = new HashSet<Rent>();
        }
    
        public int tentants_id { get; set; }
        public string name { get; set; }
        public string contact_phone { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
